query getCollection(
  $handle: String!
  $items: Int!
  $variants: Int!
  $sortKey: ProductCollectionSortKeys
  $reverse: Boolean
) {
  collection(handle: $handle) {
    ...collection
    products(sortKey: $sortKey, reverse: $reverse, first: $items) {
      edges {
        node {
          ...product
          variants(first: $variants) {
            nodes {
              id
              availableForSale
              price {
                amount
                currencyCode
              }
              selectedOptions {
                name
                value
              }
            }
          }
        }
      }
    }
  }
}

query getCollections($first: Int!) {
  collections(first: $first, sortKey: TITLE) {
    edges {
      node {
        ...collection
      }
    }
  }
}
