const typography = {
  h1: {
    fontFamily: "Manrope",
    fontSize: "3.5rem",
    fontStyle: "normal",
    fontWeight: "700",
    lineHeight: "3.625rem" /* 103.571% */,
    letterSpacing: "0.125rem",
  },
  h2: {
    fontFamily: "Manrope",
    fontSize: "2.5rem",
    fontStyle: "normal",
    fontWeight: "700",
    lineHeight: "2.75rem" /* 110% */,
    letterSpacing: "0.08931rem",
  },
  h3: {
    fontFamily: "Manrope",
    fontSize: "2rem",
    fontStyle: "normal",
    fontWeight: "700",
    lineHeight: "2.25rem" /* 112.5% */,
    letterSpacing: "0.07144rem",
  },
  h4: {
    fontFamily: "Manrope",
    fontSize: "1.75rem",
    fontStyle: "normal",
    fontWeight: "700",
    lineHeight: "normal",
    letterSpacing: "0.125rem",
  },
  h5: {
    fontFamily: "Manrope",
    fontSize: "1.5rem",
    fontStyle: "normal",
    fontWeight: "700",
    lineHeight: "normal",
    letterSpacing: "0.10713rem",
  },
  h6: {
    fontFamily: "Manrope",
    fontSize: "1.125rem",
    fontStyle: "normal",
    fontWeight: "700",
    lineHeight: "normal",
    letterSpacing: "0.08038rem",
  },
  overline: {
    fontFamily: "Manrope",
    fontSize: "0.875rem",
    fontStyle: "normal",
    fontWeight: "400",
    lineHeight: "normal",
    letterSpacing: "0.625rem",
  },
  subTitle: {
    fontFamily: "Manrope",
    fontSize: "0.8125rem",
    fontStyle: "normal",
    fontWeight: "700",
    lineHeight: "1.5625rem" /* 192.308% */,
    letterSpacing: "0.05806rem",
  },
  body: {
    fontFamily: "Manrope",
    fontSize: "0.9375rem",
    fontStyle: "normal",
    fontWeight: "500",
    lineHeight: "1.5625rem",
  },
};

export default typography;
